backend:
    name: git-gateway
    branch: master
 
media_folder: "static/PostImages"
public_folder: "/images"
 
collections:
    - name: "posts"
      label: "Posts"
      folder: "content/en/posts/"
      create: true
      slug: "{{year}}-{{slug}}"
      fields:
        # - {label: "Author", name: "author", widget: "string", default: "Ritschie"}
        - {label: "Title", name: "title", widget: "string", required: true}
        - {label: "Publish Date", name: "date", widget: "date", required: true}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Draft", name: "draft", widget: "boolean", default: true}
        - {label: "Hide Toc", name: "hideToc", widget: "boolean", default: false}
        - {label: "Enable Toc", name: "enableToc", widget: "boolean", default: true}
        - {label: "Enable Toc Content", name: "enableTocContent", widget: "boolean", default: false}
        - {label: "Author", name: "author", widget: "string", default: "Hristo Vuchev"}
        - {label: "Author Emoji", name: "authorEmoji", widget: "string" }
        - {label: "Post Image", name: "image", widget: image, required: true}
        - {label: "Tags", name: "tags", widget: "list", required: true}
        - {label: "Categories", name: "categories", widget: "list", required: true}
        - {label: "Series", name: "series", widget: "list", required: true}
        - {label: "Body", name: "body", widget: "markdown", required: true}
