backend:
 name: git-gateway
 branch: master
 
 media_folder: "static/PostImages"
 public_folder: "/images"
 
 collections:
    - name: "posts"
        label: "Posts"
        folder: "content/en/posts"
        create: true
        slug: "{{year}}-{{slug}}"
        fields:
            - {label: "Title", name: "title", widget: "string", required: true}
            - {label: "Description", name: "description", widget: "string"}
            - {label: "Draft", name: "draft", widget: "boolean", default: true}
            - {label: "Hide Toc", name: "hideToc", widget: "boolean", default: false}
            - {label: "Enable Toc", name: "enableToc", widget: "boolean", default: true}
            - {label: "Enable Toc Content", name: "enableTocContent", widget: "boolean", default: false}
            - {label: "Post Image", name: "image", widget: image, required: true}
            - {label: "Tags", name: "tags", widget: "list", required: true}
            - {label: "Categories", name: "categories", widget: "list", required: true}
            - {label: "Series", name: "series", widget: "list", required: true}
